name: Code Coverage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore Solutions
        run: |
          dotnet restore One/One.sln
          dotnet restore Two/Two.sln

      - name: Build Solutions
        run: |
          dotnet build One/One.sln --configuration Release --no-restore
          dotnet build Two/Two.sln --configuration Release --no-restore

      - name: Test and collect coverage for One solution
        run: |
          dotnet test One/One.sln --configuration Release --no-build --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura

      - name: Test and collect coverage for Two solution
        run: |
          dotnet test Two/Two.sln --configuration Release --no-build --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: "**/TestResults/*/coverage.cobertura.xml"
