name: SonarCloud Analysis

on:
  push:
    branches:
      - master

jobs:
  sonarCloud:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Create coverage directory
      run: |
            mkdir coverage

            dotnet tool install --global dotnet-sonarscanner

            dotnet sonarscanner begin  /k:"KostiaBohatyrov_MultSolutions" /o:"kostiabohatyrov" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="coverage/coverageOne.xml,coverage/coverageTwo.xml"
      
            dotnet restore One/One.sln
            dotnet restore Two/Two.sln

            dotnet build One/One.sln --configuration Release --no-restore
            dotnet build Two/Two.sln --configuration Release --no-restore

            dotnet test One/One.sln --configuration Release --no-build --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura /p:CoverletOutput=coverage/coverageOne.xml

            dotnet test Two/Two.sln --configuration Release --no-build --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura /p:CoverletOutput=coverage/coverageTwo.xml

            dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
